steps:
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["test"]
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]
  - name: gcr.io/demo/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/demo", "--build-arg=JAR_FILE=target/demo-1.0.0.jar", "."]
images: ["gcr.io/$PROJECT_ID/demo"]
